apiVersion: v1
kind: Secret
metadata:
  name: drone
  namespace: staging
type: Opaque
data:
  DRONE_GITHUB_CLIENT: echo -n 'drone_github_client' | base64
  DRONE_GITHUB_SECRET: echo -n 'drone_github_secret' | base64
  DRONE_SECRET: echo -n 'drone_secret' | base64
