apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: drone
  namespace: staging
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - staging-drone.theartwishlist.com
    secretName: drone-tls
  rules:
  - host: staging-drone.theartwishlist.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: drone-ui
          servicePort: 80
